using NHibernate.Mapping.ByCode.Conformist;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Volvo.VSSMaintenance.UserDomain.DomainLayer.Entities;

namespace Volvo.VSSMaintenance.UserDomain.InfrastructureLayer.Mappings
{
    public class RUSettingsInfoMap: ClassMapping<RUSettingsInfo>
    {
        public RUSettingsInfoMap()
        {
            Table("[VuRUSettingsDetail]");
            Schema("[dbo]");
            Lazy(true);
            Id(x => x.RUSettingsId);
            Property(x => x.OrganisationId);
            Property(x => x.ActivateQuotedFlow);
            Property(x => x.VATFactorPercentage);
            Property(x => x.QuotePrefix);
            Property(x => x.QuoteSuffix);
            Property(x => x.CalculationModel);
            Property(x => x.CalculationModelTradeInFlag);
            Property(x => x.GDSOrderFile);
            Property(x => x.OMOrderFile);
            Property(x => x.GDSOrderFile);
            Property(x => x.OMOrderFile);
            Property(x => x.AdministratorId);
            Property(x => x.OrderFileTypeId);
            Property(x => x.OrderFileType);
            Property(x => x.DefaultBuyerTypeId);
            Property(x => x.DefaultBuyerType);
            Property(x => x.ObjVersion);
            Property(x => x.UseRUSignerInDoc);
            Property(x => x.UseTitleInDoc);
            Property(x => x.ExtraSalePercentage);
            Property(x => x.PrivateDealer);
            Property(x => x.DefaultLanguage);
            Property(x => x.IMAccess);
            Property(x => x.CMAccess);
            Property(x => x.WISPerfAccess);
            Property(x => x.FCAccess);
            Property(x => x.CQOnlineAccess);
            Property(x => x.SAMAccess);
            Property(x => x.VATFactorTradeIn);
            Property(x => x.UTSAccess);
            Property(x => x.ManualTradeIn);
            Property(x => x.AvailableVehicleContactName);
            Property(x => x.AvailableVehicleContactEMail);
            Property(x => x.AvailableVehicleContactPhone);
            Property(x => x.CoPilotAccess);
            Property(x => x.ShowLocalCostWithoutSalesPrice);
            Property(x => x.UseRUinDocument);
            Property(x => x.IncludeHeader);
            Property(x => x.IncludeFooter);
            Property(x => x.ShowVersion);
            Property(x => x.ShowAlternative);
            Property(x => x.Active);
            Property(x => x.VatIncludedByDefault);
            Property(x => x.IncludeOverAllowanceToSalesPrice);
            Property(x => x.TruckFinderAccess);
            Property(x => x.IncludeCustomerSigner);
            Property(x => x.SplitOrderToGDS);
            Property(x => x.ExternalCounterNumber);
            Property(x => x.ShowDecimals);
            Property(x => x.FooterTypeId);
            Property(x => x.FooterType);
            Property(x => x.PriceCalculationTypeId);
            Property(x => x.PriceCalculationType);
            Property(x => x.DoNotDisplayVatTax);
            Property(x => x.TAOrderFile);
            Property(x => x.OPTAccess);
            Property(x => x.TDIAccess);
            Property(x => x.TQAccess);
            Property(x => x.ShowSoftOfferPreLetter);
            Property(x => x.InvoiceType);
            Property(x => x.DealerRegionId);
            Property(x => x.TIAAccess);
            Property(x => x.ReportOutputFormat);
            Property(x => x.ExcludeExtraInvoice);
            Property(x => x.NTLAccess);
            Property(x => x.NATWisPerf);
            Property(x => x.CustomerView);
            Property(x => x.SecondaryConcessionEnabled);
            Property(x => x.TaxSettings);
            Property(x => x.ActivateCreditControl);
            Property(x => x.NoOrderSystem);
            Property(x => x.IncludeTaxCalculationSettings);
            Property(x => x.InvoiceTo);
            Property(x => x.RTFAccess);
            Property(x => x.MCApprovalCustomer);
            Property(x => x.IsSupportListPrice);
            Property(x => x.CreditPortalAccess);
            Property(x => x.ShowPriceInTechnicalSpecification);
            Property(x => x.ShowWeightInTechnicalSpecification);
            Property(x => x.IncludeCustomerAddress);
            Property(x => x.IncludeSignature3);
            Property(x => x.IncludeSignature4);
            Property(x => x.IncludeDealerAddress);
            Property(x => x.ShowSymbolInTechnicalSpecification);
            Property(x => x.ShowFamilyInTechnicalSpecification);
            Property(x => x.Signature3);
            Property(x => x.Signature4);
            Property(x => x.OmitPagebreaks);
            Property(x => x.CalculationScreenLayoutId);
            Property(x => x.CalculationScreenLayout);
            Property(x => x.IncludeDateForQuote);
            Property(x => x.IncludeDateForOrder);
            Property(x => x.VECTOAccess);
            Property(x => x.CMRussiaAccess);
        }
    }
}
